import { Suspense } from 'react'
import './globals.css'
import { Gabarito } from 'next/font/google'
import Loading from './Loading'

const gabarito = Gabarito({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={gabarito.className} suppressHydrationWarning={true}>
        <Suspense fallback={<Loading />}>
          {children}
        </Suspense>
      </body>
    </html>
  )
}
